version: '3.8' 
services: 
    arangodb: 
        build: ./arangodb 
        ports: 
            - 8529:8529 
    backend: 
        build: ./backend 
        ports: 
            - 5000:5000 
        depends_on:
            - "arangodb"
    frontend: 
        build: ./frontend 
        ports: 
            - 8080:80
        depends_on:
            - "backend"
